//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSMSTBRND
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KDSCMSMSTBRND()
        {
            this.KDSCMSSKULINK = new HashSet<KDSCMSSKULINK>();
        }
    
        public string BRNDBRNDID { get; set; }
        public string BRNDDESC { get; set; }
        public Nullable<short> BRNDINTF { get; set; }
        public System.DateTime BRNDCDAT { get; set; }
        public System.DateTime BRNDMDAT { get; set; }
        public string BRNDCRBY { get; set; }
        public string BRNDMOBY { get; set; }
        public long BRNDNMOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KDSCMSSKULINK> KDSCMSSKULINK { get; set; }
    }
}
