//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSSKULINK
    {
        public int SKULINKSKUID { get; set; }
        public string SKULINKSITEID { get; set; }
        public string SKULINKBRNDID { get; set; }
        public System.DateTime SKULINKSDATE { get; set; }
        public System.DateTime SKULINKEDATE { get; set; }
        public Nullable<short> SKULINKINTF { get; set; }
        public System.DateTime SKULINKCDAT { get; set; }
        public System.DateTime SKULINKMDAT { get; set; }
        public string SKULINKCRBY { get; set; }
        public string SKULINKMOBY { get; set; }
        public long SKULINKNMOD { get; set; }
        public string SKULINKCOMP { get; set; }
    
        public virtual KDSCMSSKUH KDSCMSSKUH { get; set; }
        public virtual KDSCMSMSTBRND KDSCMSMSTBRND { get; set; }
    }
}
