//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSSITEPROF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KDSCMSSITEPROF()
        {
            this.KDSCMSPROFSITELINK = new HashSet<KDSCMSPROFSITELINK>();
            this.KDSCMSUSER = new HashSet<KDSCMSUSER>();
        }
    
        public string STPRSTPROF { get; set; }
        public string STPRSTDESC { get; set; }
        public Nullable<short> STPRINTF { get; set; }
        public System.DateTime STPRCDAT { get; set; }
        public System.DateTime STPRMDAT { get; set; }
        public string STPRCRBY { get; set; }
        public string STPRMOBY { get; set; }
        public long STPRNMOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KDSCMSPROFSITELINK> KDSCMSPROFSITELINK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KDSCMSUSER> KDSCMSUSER { get; set; }
    }
}
