//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSSLSD
    {
        public string SLSDSLID { get; set; }
        public long SLSDSLIDI { get; set; }
        public string SLSDSLNOTA { get; set; }
        public string SLSDRCPTID { get; set; }
        public short SLSDLNNUM { get; set; }
        public System.DateTime SLSDSLDATE { get; set; }
        public string SLSDSITE { get; set; }
        public int SLSDITEMID { get; set; }
        public int SLSDVRNTID { get; set; }
        public string SLSDBRCD { get; set; }
        public short SLSDSLQTY { get; set; }
        public string SLSDSKUID { get; set; }
        public decimal SLSDSLPRC { get; set; }
        public decimal SLSDTOTPRC { get; set; }
        public Nullable<decimal> SLSDDISCPC { get; set; }
        public Nullable<decimal> SLSDDISCPP { get; set; }
        public Nullable<decimal> SLSDDISCAC { get; set; }
        public Nullable<decimal> SLSDDISCAP { get; set; }
        public Nullable<decimal> SLSDMRGNC { get; set; }
        public Nullable<decimal> SLSDMRGNP { get; set; }
        public Nullable<decimal> SLSDADMC { get; set; }
        public Nullable<decimal> SLSDADMP { get; set; }
        public Nullable<decimal> SLSDDISCTOT { get; set; }
        public Nullable<decimal> SLSDSLTOT { get; set; }
        public short SLSDVAT { get; set; }
        public Nullable<decimal> SLSDVATV { get; set; }
        public string SLSDVALBY { get; set; }
        public string SLSDREJBY { get; set; }
        public string SLSDRETBY { get; set; }
        public string SLSDCOMM { get; set; }
        public short SLSDSTAT { get; set; }
        public short SLSDFLAG { get; set; }
        public Nullable<short> SLSDINTF { get; set; }
        public System.DateTime SLSDCDAT { get; set; }
        public System.DateTime SLSDMDAT { get; set; }
        public string SLSDCRBY { get; set; }
        public string SLSDMOBY { get; set; }
        public long SLSDNMOD { get; set; }
        public Nullable<decimal> SLSDSLTOTCUS { get; set; }
        public string SLSDCOMP { get; set; }
    
        public virtual KDSCMSSLSH KDSCMSSLSH { get; set; }
    }
}
