//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSPARDTABLE
    {
        public int PARDTABID { get; set; }
        public int PARDTABENT { get; set; }
        public string PARDSDESC { get; set; }
        public string PARDLDESC { get; set; }
        public short PARDSCLAS { get; set; }
        public Nullable<long> PARDVAN1 { get; set; }
        public Nullable<long> PARDVAN2 { get; set; }
        public Nullable<long> PARDVAN3 { get; set; }
        public Nullable<long> PARDVAN4 { get; set; }
        public string PARDVAC1 { get; set; }
        public string PARDVAC2 { get; set; }
        public string PARDVAC3 { get; set; }
        public Nullable<System.DateTime> PARDDATE1 { get; set; }
        public Nullable<System.DateTime> PARDDATE2 { get; set; }
        public Nullable<System.DateTime> PARDDATE3 { get; set; }
        public string PARDCOMM { get; set; }
        public Nullable<short> PARDINTF { get; set; }
        public System.DateTime PARDCDAT { get; set; }
        public System.DateTime PARDMDAT { get; set; }
        public string PARDCRBY { get; set; }
        public string PARDMOBY { get; set; }
        public long PARDNMOD { get; set; }
    }
}
