//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSMSTITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KDSCMSMSTITEM()
        {
            this.KDSCMSMSTBRCD = new HashSet<KDSCMSMSTBRCD>();
        }
    
        public int ITEMITEMID { get; set; }
        public string ITEMITEMIDX { get; set; }
        public short ITEMTYPE { get; set; }
        public string ITEMSDESC { get; set; }
        public string ITEMLDESC { get; set; }
        public string ITEMBRNDID { get; set; }
        public short ITEMINTF { get; set; }
        public System.DateTime ITEMCDAT { get; set; }
        public System.DateTime ITEMMDAT { get; set; }
        public string ITEMCRBY { get; set; }
        public string ITEMMOBY { get; set; }
        public long ITEMNMOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KDSCMSMSTBRCD> KDSCMSMSTBRCD { get; set; }
        public virtual KDSCMSMSTBRND KDSCMSMSTBRND { get; set; }
    }
}
