//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSSALES_INT
    {
        public string CMSSALNOTA { get; set; }
        public string CMSSALBRCD { get; set; }
        public Nullable<int> CMSSALQTY { get; set; }
        public int CMSSALSKU { get; set; }
        public Nullable<short> CMSSALFLAG { get; set; }
        public short CMSSALSTAT { get; set; }
        public string CMSSALCOMM { get; set; }
        public Nullable<System.DateTime> CMSSALCDAT { get; set; }
        public Nullable<System.DateTime> CMSSALMDAT { get; set; }
        public string CMSSALSITE { get; set; }
        public string CMSSALCRBY { get; set; }
        public Nullable<decimal> CMSSALAMT { get; set; }
        public decimal CMSSALSEQ { get; set; }
        public decimal CMSSALTYPE { get; set; }
        public System.DateTime CMSSALTRNDATE { get; set; }
    }
}
