//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSSKUD
    {
        public int SKUDSKUID { get; set; }
        public int SKUDSKUIDD { get; set; }
        public string SKUDSKUIDDX { get; set; }
        public string SKUDNM { get; set; }
        public short SKUDLVL { get; set; }
        public decimal SKUDVAL { get; set; }
        public Nullable<decimal> SKUDPART { get; set; }
        public short SKUDBSON { get; set; }
        public short SKUDTYPE { get; set; }
        public Nullable<short> SKUDINTF { get; set; }
        public System.DateTime SKUDCDAT { get; set; }
        public System.DateTime SKUDMDAT { get; set; }
        public string SKUDCRBY { get; set; }
        public string SKUDMOBY { get; set; }
        public long SKUDNMOD { get; set; }
        public string SKUDCOMP { get; set; }
    
        public virtual KDSCMSSKUH KDSCMSSKUH { get; set; }
    }
}
