//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSPROFSITELINK
    {
        public string PRSTSTPROF { get; set; }
        public string PRSTSITE { get; set; }
        public System.DateTime PRSTSDAT { get; set; }
        public System.DateTime PRSTEDAT { get; set; }
        public Nullable<short> PRSTINTF { get; set; }
        public System.DateTime PRSTCDAT { get; set; }
        public System.DateTime PRSTMDAT { get; set; }
        public string PRSTCRBY { get; set; }
        public string PRSTMOBY { get; set; }
        public long PRSTNMOD { get; set; }
    
        public virtual KDSCMSSITEPROF KDSCMSSITEPROF { get; set; }
        public virtual KDSCMSSITE KDSCMSSITE { get; set; }
    }
}
