//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSSITE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KDSCMSSITE()
        {
            this.KDSCMSPROFSITELINK = new HashSet<KDSCMSPROFSITELINK>();
            this.KDSCMSSKULINK = new HashSet<KDSCMSSKULINK>();
            this.KDSCMSSPRICE = new HashSet<KDSCMSSPRICE>();
            this.KDSCMSSLSH = new HashSet<KDSCMSSLSH>();
        }
    
        public string SITESITE { get; set; }
        public short SITESCLAS { get; set; }
        public string SITESITENAME { get; set; }
        public Nullable<short> SITESITEINTF { get; set; }
        public System.DateTime SITESITECDAT { get; set; }
        public System.DateTime SITESITEMDAT { get; set; }
        public string SITESITECRBY { get; set; }
        public string SITESITEMOBY { get; set; }
        public long SITESITENMOD { get; set; }
        public decimal SITESITEFLAG { get; set; }
        public decimal SITESITESTATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KDSCMSPROFSITELINK> KDSCMSPROFSITELINK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KDSCMSSKULINK> KDSCMSSKULINK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KDSCMSSPRICE> KDSCMSSPRICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KDSCMSSLSH> KDSCMSSLSH { get; set; }
    }
}
