//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSMSTBRCD
    {
        public string BRCDBRCDID { get; set; }
        public int BRCDITEMID { get; set; }
        public int BRCDVRNTID { get; set; }
        public short BRCDTYPE { get; set; }
        public short BRCDSTAT { get; set; }
        public System.DateTime BRCDSDAT { get; set; }
        public System.DateTime BRCDEDAT { get; set; }
        public Nullable<short> BRCDINTF { get; set; }
        public System.DateTime BRCDCDAT { get; set; }
        public System.DateTime BRCDMDAT { get; set; }
        public string BRCDCRBY { get; set; }
        public string BRCDMOBY { get; set; }
        public long BRCDNMOD { get; set; }
    
        public virtual KDSCMSMSTITEM KDSCMSMSTITEM { get; set; }
        public virtual KDSCMSMSTVRNT KDSCMSMSTVRNT { get; set; }
    }
}
