//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSCOMPANY
    {
        public string COMPID { get; set; }
        public string COMPDESC { get; set; }
        public System.DateTime COMPCDAT { get; set; }
        public System.DateTime COMPMDAT { get; set; }
        public string COMPCRBY { get; set; }
        public string COMPMOBY { get; set; }
        public long COMPNMOD { get; set; }
    }
}
