//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSSASS
    {
        public int SASSITEMID { get; set; }
        public string SASSSITEID { get; set; }
        public string SASSVRNT { get; set; }
        public Nullable<short> SASSSTAT { get; set; }
        public Nullable<short> SASSINTF { get; set; }
        public Nullable<System.DateTime> SASSCDAT { get; set; }
        public Nullable<System.DateTime> SASSMDAT { get; set; }
        public string SASSCRBY { get; set; }
        public string SASSMOBY { get; set; }
        public Nullable<long> SASSNMOD { get; set; }
    }
}
