//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSSLSH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KDSCMSSLSH()
        {
            this.KDSCMSSLSD = new HashSet<KDSCMSSLSD>();
        }
    
        public string SLSHSLID { get; set; }
        public long SLSHSLIDI { get; set; }
        public string SLSHSLNOTA { get; set; }
        public string SLSHRCPTID { get; set; }
        public System.DateTime SLSHSLDATE { get; set; }
        public string SLSHSITE { get; set; }
        public string SLSHVALBY { get; set; }
        public string SLSHREJBY { get; set; }
        public string SLSHRETBY { get; set; }
        public string SLSHCOMM { get; set; }
        public short SLSHSTAT { get; set; }
        public short SLSHFLAG { get; set; }
        public Nullable<short> SLSHINTF { get; set; }
        public System.DateTime SLSHCDAT { get; set; }
        public System.DateTime SLSHMDAT { get; set; }
        public string SLSHCRBY { get; set; }
        public string SLSHMOBY { get; set; }
        public long SLSHNMOD { get; set; }
    
        public virtual KDSCMSSITE KDSCMSSITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KDSCMSSLSD> KDSCMSSLSD { get; set; }
    }
}
