//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSUSER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KDSCMSUSER()
        {
            this.KDSCMSSITELINK = new HashSet<KDSCMSSITELINK>();
        }
    
        public string USERUSID { get; set; }
        public string USERUSNM { get; set; }
        public string USERPASW { get; set; }
        public string USERUSDSC { get; set; }
        public short USERSTAT { get; set; }
        public System.DateTime USERSDAT { get; set; }
        public System.DateTime USEREDAT { get; set; }
        public short USERTYPE { get; set; }
        public string USERIMEI { get; set; }
        public string USERACPROF { get; set; }
        public string USERMEPROF { get; set; }
        public string USERSTPROF { get; set; }
        public Nullable<short> USERINTF { get; set; }
        public System.DateTime USERCDAT { get; set; }
        public System.DateTime USERMDAT { get; set; }
        public string USERCRBY { get; set; }
        public string USERMOBY { get; set; }
        public long USERNMOD { get; set; }
        public string USERTOKEN { get; set; }
        public string USERCOMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KDSCMSSITELINK> KDSCMSSITELINK { get; set; }
    }
}
