//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSSKUH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KDSCMSSKUH()
        {
            this.KDSCMSSKUD = new HashSet<KDSCMSSKUD>();
            this.KDSCMSSKULINK = new HashSet<KDSCMSSKULINK>();
        }
    
        public int SKUHSKUID { get; set; }
        public string SKUHSKUIDX { get; set; }
        public string SKUHSDES { get; set; }
        public string SKUHLDES { get; set; }
        public System.DateTime SKUHSDAT { get; set; }
        public System.DateTime SKUHEDAT { get; set; }
        public Nullable<short> SKUHINTF { get; set; }
        public System.DateTime SKUHCDAT { get; set; }
        public System.DateTime SKUHMDAT { get; set; }
        public string SKUHCRBY { get; set; }
        public string SKUHMOBY { get; set; }
        public long SKUHNMOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KDSCMSSKUD> KDSCMSSKUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KDSCMSSKULINK> KDSCMSSKULINK { get; set; }
    }
}
