//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDSCMSMSTVRNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KDSCMSMSTVRNT()
        {
            this.KDSCMSSPRICE = new HashSet<KDSCMSSPRICE>();
        }
    
        public int VRNTITEMID { get; set; }
        public int VRNTVRNTID { get; set; }
        public string VRNTVRNTIDX { get; set; }
        public string VRNTSDESC { get; set; }
        public string VRNTLDESC { get; set; }
        public Nullable<short> VRNTSTAT { get; set; }
        public Nullable<short> VRNTDINTF { get; set; }
        public System.DateTime VRNTCDAT { get; set; }
        public System.DateTime VRNTMDAT { get; set; }
        public string VRNTCRBY { get; set; }
        public string VRNTMOBY { get; set; }
        public long VRNTNMOD { get; set; }
        public string VRNTCOMP { get; set; }
    
        public virtual KDSCMSMSTITEM KDSCMSMSTITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KDSCMSSPRICE> KDSCMSSPRICE { get; set; }
    }
}
